version: '3.5'

networks:
  internal:
    name: tradetrust-document-store-internal

x-services:


  localstack: &localstack
    image: localstack/localstack
    container_name: tradetrust-localstack
    environment:

      EDGE_PORT: 10001
      PORT_WEB_UI: 9999
      HOSTNAME_EXTERNAL: tradetrust-localstack
      LOCALSTACK_HOSTNAME: tradetrust-localstack
      SERVICES: sqs,s3,iam,cloudwatch
      DEFAULT_REGION: us-east-1

      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretaccess

    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'


  ganache-cli: &ganache-cli
    image: trufflesuite/ganache-cli
    container_name: tradetrust-ganache-cli
    networks:
      - internal
    command: >
        ganache-cli
        --hostname 0.0.0.0
        --port 8585
        --networkId 15
        --hardfork petersburg
        --blockTime 0
        --accounts 5
        --unlock "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
        --deterministic
        --mnemonic "myth like bonus scare over problem client lizard pioneer submit female collect"


  monitoring: &monitoring
    image: tradetrust/monitoring
    container_name: tradetrust-monitoring
    build:
      context: "${dockerstagedir:-.}/monitoring"
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - "/monitoring/node_modules"
      - "${dockerstagedir:-.}/monitoring:/monitoring"
    env_file:
      - aws.local.env
    environment:
      HTTP_BLOCKCHAIN_ENDPOINT: http://tradetrust-ganache-cli:8585
      ACCOUNT_ADDRESS: "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"


  document-store-contract: &document-store-contract
    image: tradetrust/document-store-contract
    container_name: tradetrust-document-store-contract
    build:
      context: "${dockerstagedir:-.}/document-store-contract"
      dockerfile: Dockerfile
      args:
        DOCUMENT_STORE_MASTER_COMMIT: 65092f8cfcc06622a75548e183b08e1c9a8fee21
    networks:
      - internal
    volumes:
      - "${dockerstagedir:-.}/document-store-contract/scripts/truffle-config.js:/document-store-contract/truffle-config.js"
      - "${dockerstagedir:-.}/document-store-contract/scripts/deploy-contracts.js:/document-store-contract/deploy-contracts.js"
      - "${dockerstagedir:-.}/document-store-contract/addresses:/document-store-contract/addresses"
      - "${dockerstagedir:-.}/document-store-contract/abi:/document-store-contract/abi"
    environment:
      DOCUMENT_STORE_NAME: Development
      ADDRESSES_DIR: /document-store-contract/addresses
    depends_on:
      - ganache-cli


  document-store-service-environment: &document-store-service-environment
    image: tradetrust/ts-document-store-worker-environment
    container_name: ts-document-store-worker-environment
    build:
      context: ${dockerstagedir:-.}/ts-document-store-worker
      dockerfile: Dockerfile
      target: environment
    networks:
      - internal
    volumes:
      - /document-store-worker/node_modules
      - '${dockerstagedir:-.}/ts-document-store-worker:/document-store-worker/'
      - '${dockerstagedir:-.}/document-store-contract:/document-store-contract'
    env_file:
      - aws.local.env
      - document-store-service.local.env


  document-store-service-production: &document-store-service-production
    image: tradetrust/ts-document-store-worker-production
    container_name: ts-document-store-worker-production
    build:
      context: ${dockerstagedir:-.}/ts-document-store-worker
      dockerfile: Dockerfile
      target: production
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/document-store-contract:/document-store-contract'
    env_file:
      - aws.local.env
      - document-store-service.local.env
services:
  localstack:
    <<: *localstack

  ganache-cli:
    <<: *ganache-cli

  monitoring:
    <<: *monitoring

  document-store-contract:
    <<: *document-store-contract


  batched-issue-worker:
    <<: *document-store-service-production
    container_name: batched-issue-worker
    command: batched-issue-worker.js
    environment:

      STARTUP_DELAY_SECONDS: 60

      UNPROCESSED_QUEUE_URL: http://tradetrust-localstack:10001/queue/issue-unprocessed
      INVALID_BUCKET_NAME: issue-invalid
      UNPROCESSED_BUCKET_NAME: issue-unprocessed
      BATCH_BUCKET_NAME: issue-batch
      ISSUED_BUCKET_NAME: issued

      # integer value >= 1 and <= 20
      # 20 is an upper limit that aws sdk has
      MESSAGE_WAIT_TIME: 10
      MESSAGE_VISIBILITY_TIMEOUT: 60
      TRANSACTION_TIMEOUT_SECONDS: 600
      TRANSACTION_CONFIRMATION_THRESHOLD: 1

      # integer only value
      GAS_PRICE_LIMIT_GWEI: 200
      # positive float value >= 1.1
      GAS_PRICE_MULTIPLIER: 1.2
      # 100 MB
      BATCH_SIZE_BYTES: 104857600
      # 30 sec
      BATCH_TIME_SECONDS: 30
      # number of attempts and interval between them in case of an unexpected error in RestoreBatch task
      RESTORE_ATTEMPTS: 10
      RESTORE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in ComposeBatch task
      COMPOSE_ATTEMPTS: 10
      COMPOSE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in SaveIssuedBatch task
      SAVE_ATTEMPTS: 10
      SAVE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in IssueBatch task
      ISSUE_ATTEMPTS: 10
      ISSUE_ATTEMPTS_INTERVAL_SECONDS: 60
      REVOKE_ATTEMPTS: 10
      REVOKE_ATTEMPTS_INTERVAL_SECONDS: 60


  batched-revoke-worker:
    <<: *document-store-service-production
    container_name: batched-revoke-worker
    command: batched-revoke-worker.js
    environment:
      STARTUP_DELAY_SECONDS: 60

      UNPROCESSED_QUEUE_URL: http://tradetrust-localstack:10001/queue/revoke-unprocessed
      INVALID_BUCKET_NAME: revoke-invalid
      UNPROCESSED_BUCKET_NAME: revoke-unprocessed
      BATCH_BUCKET_NAME: revoke-batch
      REVOKED_BUCKET_NAME: revoked

      # integer value >= 1 and <= 20
      # 20 is an upper limit that aws sdk has
      MESSAGE_WAIT_TIME: 10
      MESSAGE_VISIBILITY_TIMEOUT: 60
      TRANSACTION_TIMEOUT_SECONDS: 600
      TRANSACTION_CONFIRMATION_THRESHOLD: 1

      # integer only value
      GAS_PRICE_LIMIT_GWEI: 200
      # positive float value >= 1.1
      GAS_PRICE_MULTIPLIER: 1.2
      # 100 MB
      BATCH_SIZE_BYTES: 104857600
      # 30 sec
      BATCH_TIME_SECONDS: 30
      # number of attempts and interval between them in case of an unexpected error in RestoreBatch task
      RESTORE_ATTEMPTS: 10
      RESTORE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in ComposeBatch task
      COMPOSE_ATTEMPTS: 10
      COMPOSE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in SaveIssuedBatch task
      SAVE_ATTEMPTS: 10
      SAVE_ATTEMPTS_INTERVAL_SECONDS: 60
      # number of attempts and interval between them in case of an unexpected error in IssueBatch task
      REVOKE_ATTEMPTS: 10
      REVOKE_ATTEMPTS_INTERVAL_SECONDS: 60

  system-tests:
    image: tradetrust/system-tests
    container_name: system-tests
    build:
      context: ${dockerstagedir:-.}/system-tests
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - /system-tests/node_modules
      - '${dockerstagedir:-.}/system-tests:/system-tests'
      - '${dockerstagedir:-.}/document-store-contract:/document-store-contract'
    env_file:
      - aws.local.env
      - document-store-service.local.env
