version: '3.5'

networks:
  internal:
    name: tradetrust-document-store-internal

services:

  localstack:
    image: localstack/localstack
    container_name: tradetrust-localstack
    environment:

      LAMBDA_EXECUTOR: docker-reuse
      EDGE_PORT: 10001
      PORT_WEB_UI: 9999
      HOSTNAME_EXTERNAL: tradetrust-localstack
      LOCALSTACK_HOSTNAME: tradetrust-localstack
      SERVICES: sqs,s3,iam,lambda,apigateway
      DEFAULT_REGION: us-east-1

      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretaccess

      OA_API_LAMBDA_ZIP_FILENAME: /docker-entrypoint-initaws.d/oa-api-lambda.zip
      OA_API_LAMBDA_NAME: oa-api
      OA_API_NAME: oa-api
      OA_API_ENDPOINT_FILENAME: /docker-entrypoint-initaws.d/oa-api.endpoint

    ports:
      - '9999:9999'
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'

  open-attestation-api:
    image: tradetrust/open-attestation-api
    container_name: tradetrust-open-attestation-api
    build:
      context: ${dockerstagedir:-.}/open-attestation-api
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/aws'
      - '${dockerstagedir:-.}/open-attestation-api:/open-attestation-api/'
      - /document-store-api/node_modules
    environment:
      CONTAINER_MODE: lambda
      LAMBDA_ZIP_FILENAME: /aws/oa-api-lambda.zip

  document-store-worker:
    image: tradetrust/document-store-worker
    container_name: tradetrust-document-store-worker
    build:
      context: ${dockerstagedir:-.}/document-store-worker
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/document-store-contract:/document-store-contract'
      - '${dockerstagedir:-.}/document-store-worker:/document-store-worker/'
      - '${dockerstagedir:-.}/localstack:/aws'
    depends_on:
      - localstack
    environment:

      # SENTRY_DSN
      # SENTRY_ENVIRONMENT
      # SENTRY_RELEASE


      SLEEP: 30
      CONTAINER_MODE: test

      WORKER_POLLING_INTERVAL_SECONDS: 5
      WORKER_POLLING_MAX_NUMBER_OF_MESSAGES: 1
      WORKER_POLLING_MESSAGE_WAIT_TIME_SECONDS: 0
      WORKER_POLLING_VISIBILITY_TIMEOUT: 60

      OPEN_ATTESTATION_ENDPOINT: /aws/oa-api.endpoint

      BLOCKCHAIN_ENDPOINT: 'wss://ropsten.infura.io/ws/v3/f83e77be0cc14688bc3f8e74576b244a'

      AWS_ENDPOINT_URL: http://tradetrust-localstack:10001
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretaccess
      AWS_DEFAULT_REGION: us-east-1

      DOCUMENT_STORE_ABI: /document-store-contract/abi/DocumentStore.json
      DOCUMENT_STORE_ADDRESS: /document-store-contract/addresses/DocumentStore.address
      DOCUMENT_STORE_OWNER_PUBLIC_KEY: "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
      DOCUMENT_STORE_OWNER_PRIVATE_KEY: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"

      UNPROCESSED_QUEUE_URL: http://tradetrust-localstack:10001/queue/unprocessed
      UNPROCESSED_BUCKET_NAME: unprocessed
      ISSUED_BUCKET_NAME: issued
