openapi: 3.0.0
info:
  version: '1.0'
  title: Open Attestation Schema v2
paths: {}
components:
  schemas:
    identityProof:
      type: object
      properties:
        type:
          type: string
          enum:
            - DNS-TXT
        location:
          type: string
          description: Url of the website referencing to document store
      required:
        - type
        - location
      additionalProperties: false
    issuer:
      type: object
      properties:
        name:
          type: string
          description: Issuer's name
        identityProof:
          $ref: '#/components/schemas/identityProof'
      required:
        - name
        - identityProof
      additionalProperties: true
    documentStore:
      allOf:
        - $ref: '#/components/schemas/issuer'
        - type: object
          properties:
            documentStore:
              type: string
              pattern: '^0x[a-fA-F0-9]{40}$'
              description: Smart contract address of document store
          required:
            - documentStore
    certificateStore:
      type: object
      properties:
        name:
          type: string
          description: Issuer's name
        certificateStore:
          type: string
          pattern: '^0x[a-fA-F0-9]{40}$'
          description: Smart contract address of certificate store. Same as documentStore
      required:
        - name
        - certificateStore
      additionalProperties: true
    tokenRegistry:
      allOf:
        - $ref: '#/components/schemas/issuer'
        - type: object
          properties:
            tokenRegistry:
              type: string
              pattern: '^0x[a-fA-F0-9]{40}$'
              description: Smart contract address of token registry
          required:
            - tokenRegistry
    document:
      type: object
      properties:
        id:
          type: string
          description: 'Internal reference, usually serial number, of this document'
        $template:
          oneOf:
            - type: string
            - type: object
              properties:
                name:
                  type: string
                  description: Template name to be use by template renderer to determine the template to use
                type:
                  type: string
                  description: Type of renderer template
                  enum:
                    - EMBEDDED_RENDERER
                url:
                  type: string
                  description: URL of a decentralised renderer to render this document
              required:
                - name
                - type
        documentUrl:
          type: string
          description: URL of the stored tt document
        issuers:
          type: array
          items:
            type: object
            title: issuer
            oneOf:
              - $ref: '#/components/schemas/tokenRegistry'
              - $ref: '#/components/schemas/documentStore'
              - $ref: '#/components/schemas/certificateStore'
              - allOf:
                  - $ref: '#/components/schemas/issuer'
                  - not:
                      anyOf:
                        - required:
                            - certificateStore
                        - required:
                            - tokenRegistry
                        - required:
                            - documentStore
          minItems: 1
        recipient:
          type: object
          properties:
            name:
              type: string
              description: Recipient's name
          additionalProperties: true
        attachments:
          type: array
          items:
            type: object
            properties:
              filename:
                type: string
                description: 'Name of attachment, with appropriate extensions'
              type:
                type: string
                description: Type of attachment
                enum:
                  - application/pdf
                  - image/png
                  - image/jpeg
                  - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                  - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
              data:
                type: string
                description: Base64 encoding of attachment
            required:
              - filename
              - type
              - data
            additionalProperties: false
      required:
        - issuers
      additionalProperties: true
